### ISSUE TITLE
Picker - Spinning

### ISSUE THREAD

**Issue by hernangonzalez** [floriangbh/FacebookImagePicker#2]
Hi,

Why does the picker gets cleared on selection? It then remains with an endless spinner, not really waiting for anything.

Thanks,
H.

**Comment by floriangbh** [comment]
Hello,
When image is selected, the picker download the selected picture in source quality. When it's done the success delegate fonction are performed (didSelectImage). 

You need to dismiss the picker as you cas see in the readme : 

```
func facebookImagePicker(imagePicker: UIViewController, didSelectImage image: UIImage?, WithUrl url: String) {
    imagePicker.dismiss(animated: true, completion: nil) // -> This line :-)
    // Do whatever you whant with the picked image or url ...
}
```

But, it's probably better if the picker are automatically dismiss ?

**Comment by hernangonzalez** [comment]
I see what you mean. I guess in this context (since it is not usable once the collection is cleared), it should _dismis_, or do not clear the collection. thanks.

**Comment by floriangbh** [comment]
The picker is now automatically dismiss in the 1.0.8 pod version ! 
Thank your @hernangonzalez :)

**Comment by jarrillaga** [comment]
Your library is great !!

The dismiss functionality that you added, is in the example scope and not in the source of the ImagePicker, isn´t it ?

On the other hand, it will be very interesting to support multiple selection of photos. In order to achieve this, you need to add a property in order to support or not multiple selection , in the didSelect handler you need to code the selection/non-selection (add/remover border and add/remove from an array of selected images) and finally you need to add a button in the navigation bar in order to "save" the selection. It will call a new delegate method which returns the collection of selected images. I think that this features is easy and i will be very helpful. 

Cheers !

**Comment by floriangbh** [comment]
I just tried with `pod try` and I can't reproduce this issue.
Can you please post your code ? (init/show/delegate implementation)

**Comment by jarrillaga** [comment]
I edited my post because I think that I undestood:

Your library is great !!

The dismiss functionality that you added, is in the example scope and not in the source of the ImagePicker, isn´t it ?

On the other hand, it will be very interesting to support multiple selection of photos. In order to achieve this, you need to add a property in order to support or not multiple selection , in the didSelect handler you need to code the selection/non-selection (add/remover border and add/remove from an array of selected images) and finally you need to add a button in the navigation bar in order to "save" the selection. It will call a new delegate method which returns the collection of selected images. I think that this features is easy and i will be very helpful.

Cheers !

**Comment by floriangbh** [comment]
Since the 1.0.8 pod version the picker are automatically dismiss (in the exemple and in the source) check the last version, I think you have probably an old version ? 

I will add this functionality in the coming soon features :)

**Comment by jarrillaga** [comment]
Cool !! I just downloaded the last pod and this line is not in the source code: 

```
             if let httpResponse = response as? HTTPURLResponse, httpResponse.statusCode != 200 {
                  self.delegate?.facebookImagePicker(imagePicker: self, didFailWithError: error)
                  **self.dismiss(animated: true, completion: nil)**
                  return
```

I have just checked that I have the latest version and I saw this change by blame. 

I think that you have to check the pod.

**Comment by floriangbh** [comment]
Really strange.. I juste made new project with pod install, and I have the good version : 

<img width="865" alt="capture d ecran 2016-11-02 a 21 26 44" src="https://cloud.githubusercontent.com/assets/14054997/19946108/4a64ae9e-a143-11e6-9549-b8bb4b497adf.png">

Maybe clean your pod cache can help ? 
https://guides.cocoapods.org/terminal/commands.html#pod_cache_clean

**Comment by jarrillaga** [comment]
I will check this. Merci beacoup @terflogag, I´ll clean the cache and I´ll try again. 
Please let me know in case you release a new version with multiple selection.

Cheers !

**Comment by floriangbh** [comment]
Let me know if you have the same issue after clean the cache. I can push another version in last resort, maybe cocoapod issue...

Of course, you can follow this issue https://github.com/terflogag/GBHFacebookImagePicker/issues/3 for multiple selection :)
